name: Run Integration Tests

on:
  pull-request:
    types: [review_requested,opened,reopened]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .ansible/collections/ansible_collections/equinix/cloud
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: .ansible/collections/ansible_collections/equinix/cloud
          ref: ${{ github.event.pull_request.head.sha }}

      - name: update packages
        run: sudo apt-get update -y

      - name: install make
        run: sudo apt-get install -y build-essential

      - name: setup python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: install dependencies
        run: pip3 install -r requirements-dev.txt -r requirements.txt

      - name: install ansible dependencies
        run: ansible-galaxy collection install amazon.aws:==1.5.1

      - name: install collection
        run: make install

      - name: replace existing keys
        run: rm -rf ~/.ansible/test && mkdir -p ~/.ansible/test && ssh-keygen -m PEM -q -t rsa -N '' -f ~/.ansible/test/id_rsa

      - name: run tests
        run: make test
        env:
          METAL_API_TOKEN: ${{ secrets.METAL_API_TOKEN }}
