name: Run Integration Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs'
      - LICENSE
    branches:
      - main
  
#  pull_request:
#    types: [review_requested,opened,reopened,synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .ansible/collections/ansible_collections/equinix/cloud
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          path: .ansible/collections/ansible_collections/equinix/cloud
          ref: ${{ github.event.pull_request.head.sha }}

      - name: setup python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: python -m pip install -r requirements-dev.txt -r requirements.txt

      - name: update apt
        run: sudo apt update
      
      - name: install parallel
        run: sudo apt install parallel

      - name: install collection
        run: make install

      - name: replace existing keys
        run: rm -rf ~/.ansible/test && mkdir -p ~/.ansible/test && ssh-keygen -m PEM -q -t rsa -N '' -f ~/.ansible/test/id_rsa


      - name: run tests
        run: make testall
        env:
          METAL_AUTH_TOKEN: ${{ secrets.METAL_AUTH_TOKEN }}
          ANSIBLE_ACC_METAL_DEDICATED_CONNECTION_ID: ${{ secrets.ANSIBLE_ACC_METAL_DEDICATED_CONNECTION_ID }}
